apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-user
  labels:
    app: nagp-user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nagp-user
  template:
    metadata:
      labels:
        app: nagp-user
    spec:
      containers:
      - name: nagp-user
        image: 3147181/user:v1
        ports:
        - containerPort: 8080 #port container exposed