apiVersion: v1
kind: Service
metadata:
  name: nagp-aggregator-service
spec:
  selector:
    app: nagp-aggregator
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
